/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_SEMI = 2,
  sym_comment = 3,
  anon_sym_PIPE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_DOT = 11,
  anon_sym_AT = 12,
  anon_sym_POUND = 13,
  anon_sym_DQUOTE = 14,
  sym__string_content = 15,
  anon_sym_SLASH = 16,
  sym_regexp_content = 17,
  sym_escape_sequence = 18,
  sym_ident = 19,
  anon_sym_DOLLAR = 20,
  anon_sym_LT = 21,
  anon_sym_GT = 22,
  sym_source = 23,
  sym_declaration = 24,
  sym_binding = 25,
  sym_rule = 26,
  sym_production = 27,
  sym_sequence = 28,
  sym_group = 29,
  sym_repetition = 30,
  sym_optional = 31,
  sym_member_access = 32,
  sym_directive = 33,
  sym_directive_ident = 34,
  sym_string = 35,
  sym_regexp = 36,
  sym_external_value = 37,
  aux_sym_source_repeat1 = 38,
  aux_sym_sequence_repeat1 = 39,
  aux_sym_string_repeat1 = 40,
  aux_sym_regexp_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_POUND] = "#",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [anon_sym_SLASH] = "/",
  [sym_regexp_content] = "regexp_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_ident] = "ident",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_source] = "source",
  [sym_declaration] = "declaration",
  [sym_binding] = "binding",
  [sym_rule] = "rule",
  [sym_production] = "production",
  [sym_sequence] = "sequence",
  [sym_group] = "group",
  [sym_repetition] = "repetition",
  [sym_optional] = "optional",
  [sym_member_access] = "member_access",
  [sym_directive] = "directive",
  [sym_directive_ident] = "directive_ident",
  [sym_string] = "string",
  [sym_regexp] = "regexp",
  [sym_external_value] = "external_value",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_regexp_repeat1] = "regexp_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_regexp_content] = sym_regexp_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_ident] = sym_ident,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_source] = sym_source,
  [sym_declaration] = sym_declaration,
  [sym_binding] = sym_binding,
  [sym_rule] = sym_rule,
  [sym_production] = sym_production,
  [sym_sequence] = sym_sequence,
  [sym_group] = sym_group,
  [sym_repetition] = sym_repetition,
  [sym_optional] = sym_optional,
  [sym_member_access] = sym_member_access,
  [sym_directive] = sym_directive,
  [sym_directive_ident] = sym_directive_ident,
  [sym_string] = sym_string,
  [sym_regexp] = sym_regexp,
  [sym_external_value] = sym_external_value,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_regexp_repeat1] = aux_sym_regexp_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_regexp_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_production] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_repetition] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym_external_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regexp_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_content = 2,
  field_name = 3,
  field_object = 4,
  field_path = 5,
  field_property = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_content] = "content",
  [field_name] = "name",
  [field_object] = "object",
  [field_path] = "path",
  [field_property] = "property",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 0},
  [2] =
    {field_name, 0},
    {field_value, 2},
  [4] =
    {field_content, 1},
  [5] =
    {field_object, 0},
    {field_property, 2},
  [7] =
    {field_path, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 23,
        '#', 22,
        '$', 31,
        '(', 14,
        ')', 15,
        '.', 20,
        '/', 26,
        ';', 10,
        '<', 32,
        '=', 9,
        '>', 33,
        '@', 21,
        '[', 18,
        '\\', 5,
        ']', 19,
        '{', 16,
        '|', 13,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 23,
        '#', 22,
        '$', 31,
        '(', 14,
        ')', 15,
        '.', 20,
        '/', 26,
        ';', 10,
        '<', 32,
        '=', 9,
        '>', 33,
        '@', 21,
        '[', 18,
        ']', 19,
        '{', 16,
        '|', 13,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_regexp_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_regexp_content);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(45),
    [sym_declaration] = STATE(21),
    [sym_binding] = STATE(31),
    [sym_rule] = STATE(31),
    [aux_sym_source_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_production] = STATE(34),
    [sym_sequence] = STATE(22),
    [sym_group] = STATE(3),
    [sym_repetition] = STATE(3),
    [sym_optional] = STATE(3),
    [sym_member_access] = STATE(9),
    [sym_directive] = STATE(43),
    [sym_directive_ident] = STATE(44),
    [sym_string] = STATE(3),
    [sym_regexp] = STATE(3),
    [sym_external_value] = STATE(3),
    [aux_sym_sequence_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(19),
    [sym_ident] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    ACTIONS(27), 5,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(4), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [44] = 11,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
    ACTIONS(34), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(52), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    ACTIONS(29), 5,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(4), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [88] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    STATE(22), 1,
      sym_sequence,
    STATE(36), 1,
      sym_production,
    STATE(3), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [131] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    STATE(22), 1,
      sym_sequence,
    STATE(35), 1,
      sym_production,
    STATE(3), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [174] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    STATE(22), 1,
      sym_sequence,
    STATE(37), 1,
      sym_production,
    STATE(3), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [217] = 11,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(21), 1,
      sym_ident,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_member_access,
    STATE(23), 1,
      sym_sequence,
    STATE(3), 7,
      sym_group,
      sym_repetition,
      sym_optional,
      sym_string,
      sym_regexp,
      sym_external_value,
      aux_sym_sequence_repeat1,
  [257] = 2,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(55), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [276] = 1,
    ACTIONS(59), 14,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [293] = 1,
    ACTIONS(61), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [309] = 1,
    ACTIONS(63), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [325] = 1,
    ACTIONS(65), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [341] = 1,
    ACTIONS(67), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [357] = 1,
    ACTIONS(69), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [373] = 1,
    ACTIONS(71), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [389] = 1,
    ACTIONS(73), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [405] = 1,
    ACTIONS(75), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [421] = 1,
    ACTIONS(77), 13,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SLASH,
      sym_ident,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [437] = 5,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_ident,
    STATE(20), 2,
      sym_declaration,
      aux_sym_source_repeat1,
    STATE(31), 2,
      sym_binding,
      sym_rule,
  [455] = 5,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym_declaration,
      aux_sym_source_repeat1,
    STATE(31), 2,
      sym_binding,
      sym_rule,
  [473] = 1,
    ACTIONS(89), 5,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [481] = 1,
    ACTIONS(91), 5,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [489] = 3,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_repeat1,
    ACTIONS(95), 2,
      sym__string_content,
      sym_escape_sequence,
  [500] = 3,
    ACTIONS(98), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      aux_sym_string_repeat1,
    ACTIONS(100), 2,
      sym__string_content,
      sym_escape_sequence,
  [511] = 3,
    ACTIONS(102), 1,
      anon_sym_SLASH,
    STATE(29), 1,
      aux_sym_regexp_repeat1,
    ACTIONS(104), 2,
      sym_regexp_content,
      sym_escape_sequence,
  [522] = 3,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_repeat1,
    ACTIONS(108), 2,
      sym__string_content,
      sym_escape_sequence,
  [533] = 3,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    STATE(26), 1,
      aux_sym_regexp_repeat1,
    ACTIONS(112), 2,
      sym_regexp_content,
      sym_escape_sequence,
  [544] = 3,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    STATE(29), 1,
      aux_sym_regexp_repeat1,
    ACTIONS(116), 2,
      sym_regexp_content,
      sym_escape_sequence,
  [555] = 1,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_ident,
  [561] = 1,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_ident,
  [567] = 1,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_ident,
  [573] = 2,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      sym_string,
  [580] = 2,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(127), 1,
      anon_sym_PIPE,
  [587] = 2,
    ACTIONS(127), 1,
      anon_sym_PIPE,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
  [594] = 2,
    ACTIONS(127), 1,
      anon_sym_PIPE,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
  [601] = 2,
    ACTIONS(127), 1,
      anon_sym_PIPE,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
  [608] = 1,
    ACTIONS(135), 1,
      sym_ident,
  [612] = 1,
    ACTIONS(137), 1,
      sym_ident,
  [616] = 1,
    ACTIONS(139), 1,
      anon_sym_GT,
  [620] = 1,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
  [624] = 1,
    ACTIONS(143), 1,
      sym_ident,
  [628] = 1,
    ACTIONS(145), 1,
      anon_sym_SEMI,
  [632] = 1,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
  [636] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
  [640] = 1,
    ACTIONS(151), 1,
      anon_sym_EQ,
  [644] = 1,
    ACTIONS(153), 1,
      sym_ident,
  [648] = 1,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
  [652] = 1,
    ACTIONS(157), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 131,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 217,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 276,
  [SMALL_STATE(11)] = 293,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 325,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 373,
  [SMALL_STATE(17)] = 389,
  [SMALL_STATE(18)] = 405,
  [SMALL_STATE(19)] = 421,
  [SMALL_STATE(20)] = 437,
  [SMALL_STATE(21)] = 455,
  [SMALL_STATE(22)] = 473,
  [SMALL_STATE(23)] = 481,
  [SMALL_STATE(24)] = 489,
  [SMALL_STATE(25)] = 500,
  [SMALL_STATE(26)] = 511,
  [SMALL_STATE(27)] = 522,
  [SMALL_STATE(28)] = 533,
  [SMALL_STATE(29)] = 544,
  [SMALL_STATE(30)] = 555,
  [SMALL_STATE(31)] = 561,
  [SMALL_STATE(32)] = 567,
  [SMALL_STATE(33)] = 573,
  [SMALL_STATE(34)] = 580,
  [SMALL_STATE(35)] = 587,
  [SMALL_STATE(36)] = 594,
  [SMALL_STATE(37)] = 601,
  [SMALL_STATE(38)] = 608,
  [SMALL_STATE(39)] = 612,
  [SMALL_STATE(40)] = 616,
  [SMALL_STATE(41)] = 620,
  [SMALL_STATE(42)] = 624,
  [SMALL_STATE(43)] = 628,
  [SMALL_STATE(44)] = 632,
  [SMALL_STATE(45)] = 636,
  [SMALL_STATE(46)] = 640,
  [SMALL_STATE(47)] = 644,
  [SMALL_STATE(48)] = 648,
  [SMALL_STATE(49)] = 652,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repetition, 3, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 3, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_value, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regexp, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_value, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_regexp_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_regexp_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, 0, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_ident, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grammar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "grammar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
