/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 4
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_PIPE = 9,
  sym_string = 10,
  sym_regexp = 11,
  sym_comment = 12,
  sym_source_file = 13,
  sym_production_definition = 14,
  aux_sym__production = 15,
  sym__option = 16,
  sym__repeatition = 17,
  sym__group = 18,
  sym__alternative = 19,
  sym__terminal = 20,
  sym__nonterminal = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym__option_repeat1 = 23,
  aux_sym__repeatition_repeat1 = 24,
  aux_sym__group_repeat1 = 25,
  alias_sym_body = 26,
  alias_sym_group = 27,
  alias_sym_option = 28,
  alias_sym_repeatition = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PIPE] = "alternative",
  [sym_string] = "string",
  [sym_regexp] = "regexp",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_production_definition] = "production_definition",
  [aux_sym__production] = "_production",
  [sym__option] = "_option",
  [sym__repeatition] = "_repeatition",
  [sym__group] = "_group",
  [sym__alternative] = "_alternative",
  [sym__terminal] = "_terminal",
  [sym__nonterminal] = "_nonterminal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__option_repeat1] = "_option_repeat1",
  [aux_sym__repeatition_repeat1] = "_repeatition_repeat1",
  [aux_sym__group_repeat1] = "_group_repeat1",
  [alias_sym_body] = "body",
  [alias_sym_group] = "group",
  [alias_sym_option] = "option",
  [alias_sym_repeatition] = "repeatition",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_string] = sym_string,
  [sym_regexp] = sym_regexp,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_production_definition] = sym_production_definition,
  [aux_sym__production] = aux_sym__production,
  [sym__option] = sym__option,
  [sym__repeatition] = sym__repeatition,
  [sym__group] = sym__group,
  [sym__alternative] = sym__alternative,
  [sym__terminal] = sym__terminal,
  [sym__nonterminal] = sym__nonterminal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__option_repeat1] = aux_sym__option_repeat1,
  [aux_sym__repeatition_repeat1] = aux_sym__repeatition_repeat1,
  [aux_sym__group_repeat1] = aux_sym__group_repeat1,
  [alias_sym_body] = alias_sym_body,
  [alias_sym_group] = alias_sym_group,
  [alias_sym_option] = alias_sym_option,
  [alias_sym_repeatition] = alias_sym_repeatition,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_production_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__production] = {
    .visible = false,
    .named = false,
  },
  [sym__option] = {
    .visible = false,
    .named = true,
  },
  [sym__repeatition] = {
    .visible = false,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym__alternative] = {
    .visible = false,
    .named = true,
  },
  [sym__terminal] = {
    .visible = false,
    .named = true,
  },
  [sym__nonterminal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__repeatition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_body] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_group] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_option] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_repeatition] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_body,
  },
  [2] = {
    [1] = alias_sym_option,
  },
  [3] = {
    [1] = alias_sym_repeatition,
  },
  [4] = {
    [1] = alias_sym_group,
  },
  [5] = {
    [0] = anon_sym_PIPE,
    [2] = anon_sym_PIPE,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__production, 2,
    aux_sym__production,
    alias_sym_body,
  sym__option, 2,
    sym__option,
    anon_sym_PIPE,
  aux_sym__option_repeat1, 2,
    aux_sym__option_repeat1,
    alias_sym_option,
  aux_sym__repeatition_repeat1, 2,
    aux_sym__repeatition_repeat1,
    alias_sym_repeatition,
  aux_sym__group_repeat1, 2,
    aux_sym__group_repeat1,
    alias_sym_group,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 2,
        '$', 5,
        '(', 12,
        ')', 13,
        '/', 3,
        ':', 7,
        '[', 8,
        ']', 9,
        '{', 10,
        '|', 14,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_regexp);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_regexp);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_regexp] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym_production_definition] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [aux_sym__production] = STATE(7),
    [sym__option] = STATE(20),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(15),
    [sym__terminal] = STATE(15),
    [sym__nonterminal] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(11),
    [sym_regexp] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(21),
    [sym__alternative] = STATE(21),
    [sym__terminal] = STATE(21),
    [sym__nonterminal] = STATE(21),
    [aux_sym__repeatition_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(24),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(30),
    [anon_sym_LPAREN] = ACTIONS(32),
    [sym_string] = ACTIONS(21),
    [sym_regexp] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(23),
    [sym__alternative] = STATE(23),
    [sym__terminal] = STATE(23),
    [sym__nonterminal] = STATE(23),
    [aux_sym__option_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(40),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(38),
    [sym_regexp] = ACTIONS(42),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(23),
    [sym__alternative] = STATE(23),
    [sym__terminal] = STATE(23),
    [sym__nonterminal] = STATE(23),
    [aux_sym__option_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_LPAREN] = ACTIONS(55),
    [sym_string] = ACTIONS(44),
    [sym_regexp] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(21),
    [sym__alternative] = STATE(21),
    [sym__terminal] = STATE(21),
    [sym__nonterminal] = STATE(21),
    [aux_sym__repeatition_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(61),
    [sym_regexp] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [aux_sym__production] = STATE(7),
    [sym__option] = STATE(20),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(15),
    [sym__terminal] = STATE(15),
    [sym__nonterminal] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(78),
    [sym_string] = ACTIONS(69),
    [sym_regexp] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__group_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(86),
    [sym_string] = ACTIONS(84),
    [sym_regexp] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__group_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(102),
    [sym_string] = ACTIONS(90),
    [sym_regexp] = ACTIONS(104),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(23),
    [sym__alternative] = STATE(23),
    [sym__terminal] = STATE(23),
    [sym__nonterminal] = STATE(23),
    [aux_sym__option_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(38),
    [sym_regexp] = ACTIONS(42),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__group_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(84),
    [sym_regexp] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [aux_sym__production] = STATE(2),
    [sym__option] = STATE(20),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(15),
    [sym__alternative] = STATE(15),
    [sym__terminal] = STATE(15),
    [sym__nonterminal] = STATE(15),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(11),
    [sym_regexp] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym__option] = STATE(28),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(21),
    [sym__alternative] = STATE(21),
    [sym__terminal] = STATE(21),
    [sym__nonterminal] = STATE(21),
    [aux_sym__repeatition_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_string] = ACTIONS(61),
    [sym_regexp] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_regexp,
    STATE(19), 1,
      sym__option,
    ACTIONS(11), 2,
      sym_string,
      sym_identifier,
    STATE(15), 5,
      sym__repeatition,
      sym__group,
      sym__alternative,
      sym__terminal,
      sym__nonterminal,
  [30] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_regexp,
    ACTIONS(107), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [49] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_regexp,
    ACTIONS(111), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [68] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_regexp,
    ACTIONS(115), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [87] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_regexp,
    ACTIONS(119), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [106] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_regexp,
    ACTIONS(123), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [125] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PIPE,
    ACTIONS(131), 1,
      sym_regexp,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [143] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_PIPE,
    ACTIONS(137), 1,
      sym_regexp,
    ACTIONS(133), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [161] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_PIPE,
    ACTIONS(143), 1,
      sym_regexp,
    ACTIONS(139), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_identifier,
  [179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_PIPE,
    ACTIONS(147), 1,
      sym_regexp,
    ACTIONS(145), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(24), 2,
      sym_production_definition,
      aux_sym_source_file_repeat1,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym_production_definition,
      aux_sym_source_file_repeat1,
  [225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_COLON,
  [239] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 30,
  [SMALL_STATE(16)] = 49,
  [SMALL_STATE(17)] = 68,
  [SMALL_STATE(18)] = 87,
  [SMALL_STATE(19)] = 106,
  [SMALL_STATE(20)] = 125,
  [SMALL_STATE(21)] = 143,
  [SMALL_STATE(22)] = 161,
  [SMALL_STATE(23)] = 179,
  [SMALL_STATE(24)] = 197,
  [SMALL_STATE(25)] = 211,
  [SMALL_STATE(26)] = 225,
  [SMALL_STATE(27)] = 232,
  [SMALL_STATE(28)] = 239,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_definition, 3, 0, 1),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__option_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__production, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production, 2, 0, 0), SHIFT_REPEAT(15),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production, 2, 0, 0), SHIFT_REPEAT(10),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production, 2, 0, 0), SHIFT_REPEAT(13),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production, 2, 0, 0), SHIFT_REPEAT(11),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__production, 2, 0, 0), SHIFT_REPEAT(15),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__option, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 3, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__group, 3, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option, 3, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__option, 3, 0, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeatition, 3, 0, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__repeatition, 3, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__alternative, 3, 0, 5),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__alternative, 3, 0, 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__production, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__production, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeatition, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__repeatition_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__group_repeat1, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__option_repeat1, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grammar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "grammar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
