/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 3
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  anon_sym_SEMI = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_PIPE = 10,
  sym_string = 11,
  sym_regexp = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym_production_definition = 15,
  sym__production = 16,
  sym__option = 17,
  sym__repeatition = 18,
  sym__group = 19,
  sym__alternative = 20,
  sym_alternative = 21,
  sym__terminal = 22,
  sym__nonterminal = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym__production_repeat1 = 25,
  aux_sym__option_repeat1 = 26,
  aux_sym__repeatition_repeat1 = 27,
  aux_sym__group_repeat1 = 28,
  alias_sym_group = 29,
  alias_sym_option = 30,
  alias_sym_repeatition = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "open",
  [anon_sym_RBRACK] = "close",
  [anon_sym_LBRACE] = "open",
  [anon_sym_RBRACE] = "close",
  [anon_sym_LPAREN] = "open",
  [anon_sym_RPAREN] = "close",
  [anon_sym_PIPE] = "separator",
  [sym_string] = "string",
  [sym_regexp] = "regexp",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_production_definition] = "production_definition",
  [sym__production] = "body",
  [sym__option] = "_option",
  [sym__repeatition] = "_repeatition",
  [sym__group] = "_group",
  [sym__alternative] = "_alternative",
  [sym_alternative] = "alternative",
  [sym__terminal] = "_terminal",
  [sym__nonterminal] = "_nonterminal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__production_repeat1] = "_production_repeat1",
  [aux_sym__option_repeat1] = "_option_repeat1",
  [aux_sym__repeatition_repeat1] = "_repeatition_repeat1",
  [aux_sym__group_repeat1] = "_group_repeat1",
  [alias_sym_group] = "group",
  [alias_sym_option] = "option",
  [alias_sym_repeatition] = "repeatition",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACK,
  [anon_sym_RBRACE] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LBRACK,
  [anon_sym_RPAREN] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_string] = sym_string,
  [sym_regexp] = sym_regexp,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_production_definition] = sym_production_definition,
  [sym__production] = sym__production,
  [sym__option] = sym__option,
  [sym__repeatition] = sym__repeatition,
  [sym__group] = sym__group,
  [sym__alternative] = sym__alternative,
  [sym_alternative] = sym_alternative,
  [sym__terminal] = sym__terminal,
  [sym__nonterminal] = sym__nonterminal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__production_repeat1] = aux_sym__production_repeat1,
  [aux_sym__option_repeat1] = aux_sym__option_repeat1,
  [aux_sym__repeatition_repeat1] = aux_sym__repeatition_repeat1,
  [aux_sym__group_repeat1] = aux_sym__group_repeat1,
  [alias_sym_group] = alias_sym_group,
  [alias_sym_option] = alias_sym_option,
  [alias_sym_repeatition] = alias_sym_repeatition,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regexp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_production_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__production] = {
    .visible = true,
    .named = true,
  },
  [sym__option] = {
    .visible = false,
    .named = true,
  },
  [sym__repeatition] = {
    .visible = false,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym__alternative] = {
    .visible = false,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym__terminal] = {
    .visible = false,
    .named = true,
  },
  [sym__nonterminal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__production_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__repeatition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_group] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_option] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_repeatition] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_close = 1,
  field_left = 2,
  field_name = 3,
  field_open = 4,
  field_right = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_left] = "left",
  [field_name] = "name",
  [field_open] = "open",
  [field_right] = "right",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 4},
  [4] = {.index = 9, .length = 4},
  [5] = {.index = 9, .length = 4},
  [6] = {.index = 13, .length = 2},
  [7] = {.index = 15, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 2, .inherited = true},
    {field_name, 0},
    {field_open, 2, .inherited = true},
  [3] =
    {field_close, 0, .inherited = true},
    {field_open, 0, .inherited = true},
  [5] =
    {field_close, 0, .inherited = true},
    {field_close, 1, .inherited = true},
    {field_open, 0, .inherited = true},
    {field_open, 1, .inherited = true},
  [9] =
    {field_close, 1, .inherited = true},
    {field_close, 2},
    {field_open, 0},
    {field_open, 1, .inherited = true},
  [13] =
    {field_close, 2},
    {field_open, 0},
  [15] =
    {field_close, 0, .inherited = true},
    {field_close, 2, .inherited = true},
    {field_left, 0},
    {field_open, 0, .inherited = true},
    {field_open, 2, .inherited = true},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = alias_sym_option,
  },
  [5] = {
    [1] = alias_sym_repeatition,
  },
  [6] = {
    [1] = alias_sym_group,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__option_repeat1, 2,
    aux_sym__option_repeat1,
    alias_sym_option,
  aux_sym__repeatition_repeat1, 2,
    aux_sym__repeatition_repeat1,
    alias_sym_repeatition,
  aux_sym__group_repeat1, 2,
    aux_sym__group_repeat1,
    alias_sym_group,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 2,
        '$', 5,
        '(', 13,
        ')', 14,
        '/', 3,
        ':', 7,
        ';', 8,
        '[', 9,
        ']', 10,
        '{', 11,
        '|', 15,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_regexp);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_regexp);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_regexp] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym_production_definition] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__production] = STATE(27),
    [sym__option] = STATE(21),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__production_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(9),
    [sym_regexp] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__option] = STATE(21),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__production_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(9),
    [sym_regexp] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(22),
    [sym__alternative] = STATE(22),
    [sym_alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__repeatition_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(24),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(30),
    [anon_sym_LPAREN] = ACTIONS(32),
    [sym_string] = ACTIONS(21),
    [sym_regexp] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__option_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(38),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(9),
    [sym_regexp] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(22),
    [sym__alternative] = STATE(22),
    [sym_alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__repeatition_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(42),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(40),
    [sym_regexp] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__option] = STATE(21),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__production_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(46),
    [anon_sym_SEMI] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(54),
    [anon_sym_LPAREN] = ACTIONS(57),
    [sym_string] = ACTIONS(46),
    [sym_regexp] = ACTIONS(60),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__option_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(66),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(74),
    [sym_string] = ACTIONS(63),
    [sym_regexp] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(24),
    [sym_alternative] = STATE(24),
    [sym__terminal] = STATE(24),
    [sym__nonterminal] = STATE(24),
    [aux_sym__group_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(80),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(82),
    [sym_string] = ACTIONS(80),
    [sym_regexp] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(24),
    [sym_alternative] = STATE(24),
    [sym__terminal] = STATE(24),
    [sym__nonterminal] = STATE(24),
    [aux_sym__group_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(92),
    [anon_sym_LPAREN] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(98),
    [sym_string] = ACTIONS(86),
    [sym_regexp] = ACTIONS(100),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(23),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(16),
    [sym_alternative] = STATE(16),
    [sym__terminal] = STATE(16),
    [sym__nonterminal] = STATE(16),
    [aux_sym__option_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(9),
    [sym_regexp] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(22),
    [sym__alternative] = STATE(22),
    [sym_alternative] = STATE(22),
    [sym__terminal] = STATE(22),
    [sym__nonterminal] = STATE(22),
    [aux_sym__repeatition_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(40),
    [sym_regexp] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym__option] = STATE(31),
    [sym__repeatition] = STATE(15),
    [sym__group] = STATE(16),
    [sym__alternative] = STATE(24),
    [sym_alternative] = STATE(24),
    [sym__terminal] = STATE(24),
    [sym__nonterminal] = STATE(24),
    [aux_sym__group_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(80),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_string] = ACTIONS(80),
    [sym_regexp] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_regexp,
    STATE(15), 1,
      sym__repeatition,
    STATE(20), 1,
      sym__option,
    ACTIONS(9), 2,
      sym_string,
      sym_identifier,
    STATE(16), 5,
      sym__group,
      sym__alternative,
      sym_alternative,
      sym__terminal,
      sym__nonterminal,
  [33] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_regexp,
    ACTIONS(103), 10,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [52] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_regexp,
    ACTIONS(107), 10,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [71] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_regexp,
    ACTIONS(111), 10,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_regexp,
    ACTIONS(115), 10,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_regexp,
    ACTIONS(119), 10,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      sym_string,
      sym_identifier,
  [128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(127), 1,
      sym_regexp,
    ACTIONS(123), 9,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_identifier,
  [149] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(131), 1,
      sym_regexp,
    ACTIONS(129), 6,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_PIPE,
    ACTIONS(135), 1,
      sym_regexp,
    ACTIONS(133), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_PIPE,
    ACTIONS(139), 1,
      sym_regexp,
    ACTIONS(137), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_string,
      sym_identifier,
  [203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_PIPE,
    ACTIONS(145), 1,
      sym_regexp,
    ACTIONS(141), 6,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_identifier,
  [221] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 1,
      sym_identifier,
    STATE(25), 2,
      sym_production_definition,
      aux_sym_source_file_repeat1,
  [235] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    STATE(25), 2,
      sym_production_definition,
      aux_sym_source_file_repeat1,
  [249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COLON,
  [279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 33,
  [SMALL_STATE(16)] = 52,
  [SMALL_STATE(17)] = 71,
  [SMALL_STATE(18)] = 90,
  [SMALL_STATE(19)] = 109,
  [SMALL_STATE(20)] = 128,
  [SMALL_STATE(21)] = 149,
  [SMALL_STATE(22)] = 167,
  [SMALL_STATE(23)] = 185,
  [SMALL_STATE(24)] = 203,
  [SMALL_STATE(25)] = 221,
  [SMALL_STATE(26)] = 235,
  [SMALL_STATE(27)] = 249,
  [SMALL_STATE(28)] = 257,
  [SMALL_STATE(29)] = 265,
  [SMALL_STATE(30)] = 272,
  [SMALL_STATE(31)] = 279,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3), SHIFT_REPEAT(22),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3), SHIFT_REPEAT(11),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3), SHIFT_REPEAT(13),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__repeatition_repeat1, 2, 0, 3), SHIFT_REPEAT(22),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3), SHIFT_REPEAT(16),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3), SHIFT_REPEAT(11),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3), SHIFT_REPEAT(13),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__production_repeat1, 2, 0, 3), SHIFT_REPEAT(16),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3), SHIFT_REPEAT(16),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3), SHIFT_REPEAT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3), SHIFT_REPEAT(12),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3), SHIFT_REPEAT(13),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__option_repeat1, 2, 0, 3), SHIFT_REPEAT(16),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__group_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option, 1, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__option, 1, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeatition, 1, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__repeatition, 1, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeatition, 3, 0, 5),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__repeatition, 3, 0, 5),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option, 3, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__option, 3, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 3, 0, 6),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__group, 3, 0, 6),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3, 0, 7),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 3, 0, 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__production_repeat1, 1, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__production_repeat1, 1, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__repeatition_repeat1, 1, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__repeatition_repeat1, 1, 0, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__option_repeat1, 1, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__option_repeat1, 1, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__group_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__group_repeat1, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_production_definition, 3, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__production, 2, 0, 2),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grammar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "grammar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
